engine: grpc
log:
  path: job.log
  level: debug
  max_age: 168
  rotation_time: 24
grpc:
  server_port: 8080
debug: True
store_type: mysql
mysql:
  ip: 192.168.1.224
  port: 3306
  user: root
  password: root
  database: job
  debug: True
